// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: vtukslxkqagbkefiaysn

class SupabaseConfig {
  static const String supabaseUrl = 'https://vtukslxkqagbkefiaysn.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0dWtzbHhrcWFnYmtlZmlheXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MzA5MzQsImV4cCI6MjA3OTAwNjkzNH0.GG9eED9vYHMS0HnmHJAlCwcgnLUF6AYs-_0nDuAml10';
}
